### ISSUE TITLE
Unity 5.3.4 freezes on launch if Relations Inspector window was open with AssetReferenceBackend in saved layout

### ISSUE THREAD

**Issue by VoxelBoy** [seldomU/AssetReferenceBackend#1]
Repro steps:
- Create new Unity project in 5.3.4
- Download Reference Inspector Demo from Asset Store
- Add AssetReferenceBackend files to Scripts/Editor
- Open Reference Inspector window
- Quit Unity
- Re-open Unity
- Freeze (application not responding)

Tested on OS X El Capitan

**Comment by seldomU** [comment]
I can reproduce it. On awake, AssetReferenceBackend saves the current scene and creates a new one. With that disabled, the freeze goes away. I'm in the middle of reworking this backend anyway, hopefully this will be fixed in the next two days.
Thanks for the report!

**Comment by VoxelBoy** [comment]
Thanks for the quick response.

**Comment by seldomU** [comment]
Should be fixed now. As a downside, only the currently active scene is processed.
